version: '3.8'

services:
  nginx:
    image: sebcontents/client
    restart: 'always'
    ports:
      - '8080:80'
    container_name: client

  spring:
    image: 0xnsky/server-spring
    restart: 'always'
    ports:
      - '5000:3000'
    container_name: server-spring
    volumes:
      - './volumefolder:/data'

  mysql:
    image: amd64/mysql
    restart: 'always'
    ports:
      - '3307:3306'
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: docker
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
